// Build script: Generates config.js from Vercel environment variables
// Run by Vercel during deployment

const fs = require('fs');
const path = require('path');

const config = {
  deepseekEndpoint: process.env.DEEPSEEK_ENDPOINT || 'https://api.deepseek.com/chat/completions',
  deepseekToken: process.env.DEEPSEEK_TOKEN || '',
  deepseekEngine: process.env.DEEPSEEK_ENGINE || 'deepseek-chat',
  elevenlabsEndpoint: process.env.ELEVENLABS_ENDPOINT || 'https://api.elevenlabs.io/v1/text-to-speech',
  elevenlabsKey: process.env.ELEVENLABS_KEY || '',
  minimaxEndpoint: process.env.MINIMAX_ENDPOINT || 'https://api.minimax.io/v1/t2a_v2',
  minimaxKey: process.env.MINIMAX_KEY || '',
  minimaxGroupId: process.env.MINIMAX_GROUP_ID || '',
  googleTtsEndpoint: process.env.GOOGLE_TTS_ENDPOINT || 'https://texttospeech.googleapis.com/v1/text:synthesize',
  googleTtsKey: process.env.GOOGLE_TTS_KEY || '',
  supabaseUrl: process.env.SUPABASE_URL || '',
  supabaseAnonKey: process.env.SUPABASE_ANON_KEY || '',
};

const content = `// Auto-generated by Vercel build – DO NOT EDIT manually
window.CONFIG = ${JSON.stringify(config, null, 2)};`;

const outputPath = path.join(__dirname, 'config.js');
fs.writeFileSync(outputPath, content);

console.log('✅ Generated config.js from environment variables');
