// Build script: Generates config.js from Vercel environment variables
// Run by Vercel during deployment

const fs = require('fs');
const path = require('path');

const config = {
  cerebrasEndpoint: process.env.CEREBRAS_ENDPOINT || 'https://api.cerebras.ai/v1/chat/completions',
  cerebrasToken: process.env.CEREBRAS_TOKEN || '',
  cerebrasEngine: process.env.CEREBRAS_ENGINE || 'qwen-3-235b-a22b-instruct-2507',
  elevenlabsEndpoint: process.env.ELEVENLABS_ENDPOINT || 'https://api.elevenlabs.io/v1/text-to-speech',
  elevenlabsKey: process.env.ELEVENLABS_KEY || '',
  supabaseUrl: process.env.SUPABASE_URL || '',
  supabaseAnonKey: process.env.SUPABASE_ANON_KEY || '',
};

const content = `// Auto-generated by Vercel build – DO NOT EDIT manually
window.CONFIG = ${JSON.stringify(config, null, 2)};`;

const outputPath = path.join(__dirname, 'config.js');
fs.writeFileSync(outputPath, content);

console.log('✅ Generated config.js from environment variables');
