// ========== AIRPORT DATA (B1 Level) ==========
const AIRPORT_DATA = {
  vocabulary: [
    { word: "Boarding pass", phonetic: "/ˈbɔːrdɪŋ pæs/", meaning: "Thẻ lên máy bay", example: "Please show me your boarding pass.", exampleVi: "Vui lòng cho tôi xem thẻ lên máy bay." },
    { word: "Check-in", phonetic: "/ˈtʃɛk ɪn/", meaning: "Làm thủ tục", example: "Where is the check-in counter?", exampleVi: "Quầy làm thủ tục ở đâu?" },
    { word: "Departure", phonetic: "/dɪˈpɑːrtʃər/", meaning: "Khởi hành", example: "The departure time is 10:30 AM.", exampleVi: "Giờ khởi hành là 10:30 sáng." },
    { word: "Arrival", phonetic: "/əˈraɪvl/", meaning: "Đến nơi", example: "What is the arrival time?", exampleVi: "Giờ đến là mấy giờ?" },
    { word: "Gate", phonetic: "/ɡeɪt/", meaning: "Cửa ra máy bay", example: "Your flight departs from gate B12.", exampleVi: "Chuyến bay khởi hành từ cửa B12." },
    { word: "Luggage", phonetic: "/ˈlʌɡɪdʒ/", meaning: "Hành lý", example: "How many pieces of luggage do you have?", exampleVi: "Bạn có bao nhiêu kiện hành lý?" },
    { word: "Carry-on", phonetic: "/ˈkæri ɒn/", meaning: "Hành lý xách tay", example: "You can bring one carry-on bag.", exampleVi: "Bạn có thể mang một túi xách tay." },
    { word: "Customs", phonetic: "/ˈkʌstəmz/", meaning: "Hải quan", example: "You need to go through customs.", exampleVi: "Bạn cần đi qua hải quan." },
    { word: "Immigration", phonetic: "/ˌɪmɪˈɡreɪʃn/", meaning: "Xuất nhập cảnh", example: "The immigration line is very long.", exampleVi: "Hàng xuất nhập cảnh rất dài." },
    { word: "Passport", phonetic: "/ˈpæspɔːrt/", meaning: "Hộ chiếu", example: "May I see your passport, please?", exampleVi: "Tôi có thể xem hộ chiếu của bạn không?" },
    { word: "Delay", phonetic: "/dɪˈleɪ/", meaning: "Chậm trễ, trì hoãn", example: "The flight has been delayed by two hours.", exampleVi: "Chuyến bay đã bị trì hoãn hai tiếng." },
    { word: "Transit", phonetic: "/ˈtræn.zɪt/", meaning: "Quá cảnh", example: "I'm in transit to London.", exampleVi: "Tôi đang quá cảnh đến London." },
    { word: "Terminal", phonetic: "/ˈtɜːrmɪnl/", meaning: "Nhà ga", example: "Which terminal is my flight?", exampleVi: "Chuyến bay ở nhà ga nào?" },
    { word: "Baggage claim", phonetic: "/ˈbæɡɪdʒ kleɪm/", meaning: "Nơi lấy hành lý", example: "The baggage claim is on the ground floor.", exampleVi: "Nơi lấy hành lý ở tầng trệt." },
    { word: "Turbulence", phonetic: "/ˈtɜːrbjələns/", meaning: "Nhiễu động (khi bay)", example: "Please fasten your seatbelt, we expect turbulence.", exampleVi: "Vui lòng thắt dây an toàn, dự kiến có nhiễu động." },
    { word: "Aisle seat", phonetic: "/aɪl siːt/", meaning: "Ghế lối đi", example: "Can I have an aisle seat, please?", exampleVi: "Tôi có thể chọn ghế lối đi không?" },
    { word: "Window seat", phonetic: "/ˈwɪndoʊ siːt/", meaning: "Ghế cạnh cửa sổ", example: "I prefer a window seat.", exampleVi: "Tôi thích ghế cạnh cửa sổ." },
    { word: "Connecting flight", phonetic: "/kəˈnɛktɪŋ flaɪt/", meaning: "Chuyến bay nối chuyến", example: "I have a connecting flight to Paris.", exampleVi: "Tôi có chuyến bay nối chuyến đến Paris." },
    // --- B1 Expanded ---
    { word: "Overhead compartment", phonetic: "/ˌoʊvərˈhɛd kəmˈpɑːrtmənt/", meaning: "Ngăn hành lý trên đầu", example: "Please store your bag in the overhead compartment.", exampleVi: "Vui lòng cất túi vào ngăn hành lý trên đầu." },
    { word: "Boarding", phonetic: "/ˈbɔːrdɪŋ/", meaning: "Lên máy bay", example: "Boarding will begin in ten minutes.", exampleVi: "Lên máy bay sẽ bắt đầu trong mười phút." },
    { word: "Declare", phonetic: "/dɪˈklɛr/", meaning: "Khai báo (hải quan)", example: "Do you have anything to declare?", exampleVi: "Bạn có gì cần khai báo không?" },
    { word: "Duty-free", phonetic: "/ˈdjuːti friː/", meaning: "Miễn thuế", example: "Let's check the duty-free shop.", exampleVi: "Mình ghé cửa hàng miễn thuế nhé." },
    { word: "Conveyor belt", phonetic: "/kənˈveɪ.ər bɛlt/", meaning: "Băng chuyền hành lý", example: "Wait for your bag at the conveyor belt.", exampleVi: "Chờ hành lý ở băng chuyền." },
    { word: "Runway", phonetic: "/ˈrʌnweɪ/", meaning: "Đường băng", example: "The plane is on the runway.", exampleVi: "Máy bay đang trên đường băng." },
    { word: "Takeoff", phonetic: "/ˈteɪkɒf/", meaning: "Cất cánh", example: "Please remain seated during takeoff.", exampleVi: "Vui lòng ngồi yên khi cất cánh." },
    { word: "Landing", phonetic: "/ˈlændɪŋ/", meaning: "Hạ cánh", example: "We will be landing in 20 minutes.", exampleVi: "Chúng ta sẽ hạ cánh trong 20 phút." },
    { word: "Cabin crew", phonetic: "/ˈkæbɪn kruː/", meaning: "Phi hành đoàn", example: "The cabin crew will assist you.", exampleVi: "Phi hành đoàn sẽ hỗ trợ bạn." },
    { word: "Emergency exit", phonetic: "/ɪˈmɜːrdʒənsi ˈɛɡzɪt/", meaning: "Lối thoát hiểm", example: "The emergency exit is behind you.", exampleVi: "Lối thoát hiểm ở phía sau bạn." },
    { word: "Life jacket", phonetic: "/laɪf ˈdʒækɪt/", meaning: "Áo phao", example: "Your life jacket is under your seat.", exampleVi: "Áo phao ở dưới ghế ngồi." },
    { word: "Seatbelt", phonetic: "/ˈsiːtbɛlt/", meaning: "Dây an toàn", example: "Please fasten your seatbelt.", exampleVi: "Vui lòng thắt dây an toàn." },
    { word: "Itinerary", phonetic: "/aɪˈtɪnərɛri/", meaning: "Lịch trình", example: "Here is my travel itinerary.", exampleVi: "Đây là lịch trình du lịch của tôi." },
    { word: "Visa", phonetic: "/ˈviːzə/", meaning: "Thị thực", example: "Do I need a visa for this country?", exampleVi: "Tôi có cần visa cho nước này không?" },
    { word: "Round trip", phonetic: "/raʊnd trɪp/", meaning: "Khứ hồi", example: "I booked a round trip ticket.", exampleVi: "Tôi đặt vé khứ hồi." },
    { word: "One-way", phonetic: "/wʌn weɪ/", meaning: "Một chiều", example: "Is this a one-way ticket?", exampleVi: "Đây là vé một chiều phải không?" },
    { word: "Layover", phonetic: "/ˈleɪoʊvər/", meaning: "Thời gian chờ nối chuyến", example: "We have a 3-hour layover in Dubai.", exampleVi: "Chúng ta có 3 tiếng chờ nối chuyến ở Dubai." },
    { word: "Currency exchange", phonetic: "/ˈkʌrənsi ɪksˈtʃeɪndʒ/", meaning: "Đổi tiền", example: "Where is the currency exchange?", exampleVi: "Quầy đổi tiền ở đâu?" },
    { word: "Jet lag", phonetic: "/dʒɛt læɡ/", meaning: "Mệt mỏi do lệch múi giờ", example: "I'm suffering from jet lag.", exampleVi: "Tôi đang bị jet lag." },
    { word: "Departure lounge", phonetic: "/dɪˈpɑːrtʃər laʊndʒ/", meaning: "Phòng chờ khởi hành", example: "Let's wait in the departure lounge.", exampleVi: "Mình chờ ở phòng chờ khởi hành nhé." },
    { word: "Security check", phonetic: "/sɪˈkjʊrɪti tʃɛk/", meaning: "Kiểm tra an ninh", example: "Please go through the security check.", exampleVi: "Vui lòng đi qua kiểm tra an ninh." },
    { word: "Flight attendant", phonetic: "/flaɪt əˈtɛndənt/", meaning: "Tiếp viên hàng không", example: "Ask the flight attendant for help.", exampleVi: "Hãy nhờ tiếp viên hàng không giúp." },
    { word: "Overhead bin", phonetic: "/ˌoʊvərˈhɛd bɪn/", meaning: "Ngăn để đồ trên cao", example: "The overhead bin is full.", exampleVi: "Ngăn để đồ trên cao đã đầy." },
    { word: "Tray table", phonetic: "/treɪ ˈteɪbl/", meaning: "Bàn gấp trên máy bay", example: "Please fold up your tray table.", exampleVi: "Vui lòng gấp bàn lại." },
    { word: "Announcement", phonetic: "/əˈnaʊnsmənt/", meaning: "Thông báo", example: "Listen to the announcement carefully.", exampleVi: "Hãy nghe thông báo cẩn thận." },
    { word: "Shuttle bus", phonetic: "/ˈʃʌtl bʌs/", meaning: "Xe buýt đưa đón", example: "Take the shuttle bus to the terminal.", exampleVi: "Đi xe buýt đưa đón đến nhà ga." },
    { word: "Check-in counter", phonetic: "/ˈtʃɛk ɪn ˈkaʊntər/", meaning: "Quầy làm thủ tục", example: "Go to check-in counter number 5.", exampleVi: "Đến quầy làm thủ tục số 5." },
    { word: "Baggage allowance", phonetic: "/ˈbæɡɪdʒ əˈlaʊəns/", meaning: "Hạn mức hành lý", example: "The baggage allowance is 23 kilograms.", exampleVi: "Hạn mức hành lý là 23 kg." },
    { word: "Excess baggage", phonetic: "/ɪkˈsɛs ˈbæɡɪdʒ/", meaning: "Hành lý vượt cân", example: "You'll have to pay for excess baggage.", exampleVi: "Bạn sẽ phải trả phí hành lý vượt cân." },
    { word: "Fragile", phonetic: "/ˈfrædʒaɪl/", meaning: "Dễ vỡ", example: "Please mark this bag as fragile.", exampleVi: "Vui lòng đánh dấu túi này là dễ vỡ." },
    { word: "Overweight", phonetic: "/ˌoʊvərˈweɪt/", meaning: "Quá cân", example: "Your bag is overweight by 3 kilos.", exampleVi: "Túi của bạn quá cân 3 kg." },
    { word: "Direct flight", phonetic: "/dɪˈrɛkt flaɪt/", meaning: "Chuyến bay thẳng", example: "Is there a direct flight to Berlin?", exampleVi: "Có chuyến bay thẳng đến Berlin không?" },
    { word: "Destination", phonetic: "/ˌdɛstɪˈneɪʃn/", meaning: "Điểm đến", example: "What is your final destination?", exampleVi: "Điểm đến cuối cùng của bạn là gì?" },
    { word: "Boarding time", phonetic: "/ˈbɔːrdɪŋ taɪm/", meaning: "Giờ lên máy bay", example: "The boarding time is 9:45 AM.", exampleVi: "Giờ lên máy bay là 9:45 sáng." },
    { word: "Cancelled", phonetic: "/ˈkænsəld/", meaning: "Bị hủy", example: "My flight has been cancelled.", exampleVi: "Chuyến bay của tôi bị hủy." },
    { word: "Reschedule", phonetic: "/ˌriːˈʃɛdjuːl/", meaning: "Đổi lịch", example: "Can I reschedule my flight?", exampleVi: "Tôi có thể đổi lịch chuyến bay không?" },
    { word: "Refund", phonetic: "/ˈriːfʌnd/", meaning: "Hoàn tiền", example: "Can I get a refund for my ticket?", exampleVi: "Tôi có thể được hoàn tiền vé không?" },
    { word: "Lounge", phonetic: "/laʊndʒ/", meaning: "Phòng chờ VIP", example: "Do you have access to the business lounge?", exampleVi: "Bạn có quyền vào phòng chờ VIP không?" },
    { word: "Trolley", phonetic: "/ˈtrɒli/", meaning: "Xe đẩy hành lý", example: "Where can I find a luggage trolley?", exampleVi: "Tôi có thể tìm xe đẩy hành lý ở đâu?" },
    { word: "Boarding gate", phonetic: "/ˈbɔːrdɪŋ ɡeɪt/", meaning: "Cửa lên máy bay", example: "Proceed to boarding gate A5.", exampleVi: "Hãy đến cửa lên máy bay A5." },
    { word: "Passport control", phonetic: "/ˈpæspɔːrt kənˈtroʊl/", meaning: "Kiểm soát hộ chiếu", example: "You must go through passport control.", exampleVi: "Bạn phải đi qua kiểm soát hộ chiếu." },
    { word: "Domestic flight", phonetic: "/dəˈmɛstɪk flaɪt/", meaning: "Chuyến bay nội địa", example: "Is this a domestic or international flight?", exampleVi: "Đây là chuyến bay nội địa hay quốc tế?" },
    { word: "International flight", phonetic: "/ˌɪntərˈnæʃənl flaɪt/", meaning: "Chuyến bay quốc tế", example: "International flights depart from Terminal 2.", exampleVi: "Chuyến bay quốc tế khởi hành từ Nhà ga 2." },
    { word: "Reservation", phonetic: "/ˌrɛzərˈveɪʃn/", meaning: "Đặt chỗ", example: "I have a reservation under my name.", exampleVi: "Tôi có đặt chỗ dưới tên tôi." },
    { word: "Confirmation number", phonetic: "/ˌkɒnfərˈmeɪʃn ˈnʌmbər/", meaning: "Mã xác nhận", example: "Do you have your confirmation number?", exampleVi: "Bạn có mã xác nhận không?" },
    { word: "Upgrade", phonetic: "/ʌpˈɡreɪd/", meaning: "Nâng hạng", example: "Would you like to upgrade to business class?", exampleVi: "Bạn có muốn nâng hạng lên thương gia không?" },
    { word: "Economy class", phonetic: "/ɪˈkɒnəmi klæs/", meaning: "Hạng phổ thông", example: "I booked an economy class ticket.", exampleVi: "Tôi đặt vé hạng phổ thông." },
    { word: "Business class", phonetic: "/ˈbɪznəs klæs/", meaning: "Hạng thương gia", example: "Business class has more legroom.", exampleVi: "Hạng thương gia có nhiều chỗ để chân hơn." },
    { word: "Pilot", phonetic: "/ˈpaɪlət/", meaning: "Phi công", example: "The pilot announced a smooth flight.", exampleVi: "Phi công thông báo chuyến bay suôn sẻ." },
    { word: "Armrest", phonetic: "/ˈɑːrmrɛst/", meaning: "Tay vịn ghế", example: "Please keep the armrest down.", exampleVi: "Vui lòng giữ tay vịn ghế hạ xuống." },
    { word: "Immigration officer", phonetic: "/ˌɪmɪˈɡreɪʃn ˈɒfɪsər/", meaning: "Nhân viên xuất nhập cảnh", example: "The immigration officer asked about my visit.", exampleVi: "Nhân viên XNC hỏi về chuyến thăm của tôi." },
    { word: "Customs declaration", phonetic: "/ˈkʌstəmz ˌdɛkləˈreɪʃn/", meaning: "Tờ khai hải quan", example: "Please fill out the customs declaration form.", exampleVi: "Vui lòng điền tờ khai hải quan." },
    { word: "Stopover", phonetic: "/ˈstɒpoʊvər/", meaning: "Dừng chân quá cảnh", example: "We have a stopover in Singapore.", exampleVi: "Chúng ta có dừng chân ở Singapore." },
    { word: "Departure board", phonetic: "/dɪˈpɑːrtʃər bɔːrd/", meaning: "Bảng thông tin khởi hành", example: "Check the departure board for updates.", exampleVi: "Kiểm tra bảng thông tin khởi hành." },
    { word: "Arrival hall", phonetic: "/əˈraɪvl hɔːl/", meaning: "Sảnh đến", example: "I'll meet you at the arrival hall.", exampleVi: "Tôi sẽ gặp bạn ở sảnh đến." },
    { word: "Claim tag", phonetic: "/kleɪm tæɡ/", meaning: "Thẻ nhận hành lý", example: "Keep your claim tag safe.", exampleVi: "Giữ thẻ nhận hành lý cẩn thận." },
    { word: "Metal detector", phonetic: "/ˈmɛtl dɪˈtɛktər/", meaning: "Máy dò kim loại", example: "Walk through the metal detector.", exampleVi: "Đi qua máy dò kim loại." },
    { word: "Boarding call", phonetic: "/ˈbɔːrdɪŋ kɔːl/", meaning: "Gọi lên máy bay", example: "This is the final boarding call.", exampleVi: "Đây là lần gọi lên máy bay cuối cùng." },
    { word: "First class", phonetic: "/fɜːrst klæs/", meaning: "Hạng nhất", example: "First class passengers may board now.", exampleVi: "Hành khách hạng nhất có thể lên máy bay." },
  ],
  conversations: [
    {
      title: "Check-in tại quầy", icon: "🛫",
      context: "Bạn đến quầy check-in tại sân bay để làm thủ tục lên máy bay.",
      dialog: [
        { speaker: "a", label: "Staff", en: "Good morning! May I see your passport and booking confirmation?", vi: "Chào buổi sáng! Tôi có thể xem hộ chiếu và xác nhận đặt vé?" },
        { speaker: "b", label: "You", en: "Sure, here you go. I have a flight to Frankfurt at 10:30.", vi: "Được, đây ạ. Tôi có chuyến bay đến Frankfurt lúc 10:30." },
        { speaker: "a", label: "Staff", en: "Thank you. Would you like a window seat or an aisle seat?", vi: "Cảm ơn. Bạn muốn ghế cửa sổ hay ghế lối đi?" },
        { speaker: "b", label: "You", en: "An aisle seat, please. And can I check in this luggage?", vi: "Ghế lối đi. Và tôi có thể gửi hành lý này không?" },
        { speaker: "a", label: "Staff", en: "Of course. Please place your bag on the scale. It weighs 22 kilos, within the limit.", vi: "Tất nhiên. Đặt túi lên cân. Túi nặng 22 kg, trong giới hạn." },
        { speaker: "b", label: "You", en: "Great. Which gate should I go to?", vi: "Tuyệt. Tôi nên đến cửa nào?" },
        { speaker: "a", label: "Staff", en: "Gate B7. Boarding starts at 9:50. Have a pleasant flight!", vi: "Cửa B7. Lên máy bay lúc 9:50. Chúc chuyến bay vui vẻ!" },
      ]
    },
    {
      title: "Qua cửa an ninh", icon: "🔍",
      context: "Bạn đi qua cửa kiểm tra an ninh tại sân bay.",
      dialog: [
        { speaker: "a", label: "Security", en: "Please remove your laptop and any liquids from your bag.", vi: "Vui lòng lấy laptop và chất lỏng ra khỏi túi." },
        { speaker: "b", label: "You", en: "Do I need to take off my shoes as well?", vi: "Tôi có cần cởi giày ra không?" },
        { speaker: "a", label: "Security", en: "Yes, please. And remove your belt too.", vi: "Vâng. Và cởi thắt lưng nữa." },
        { speaker: "b", label: "You", en: "Okay, here you go.", vi: "Được rồi, đây ạ." },
        { speaker: "a", label: "Security", en: "Please step through the scanner. You're all clear. Have a nice trip!", vi: "Vui lòng đi qua máy quét. Bạn qua rồi. Chúc chuyến đi vui vẻ!" },
      ]
    },
    {
      title: "Hỏi đường tại sân bay", icon: "🗺️",
      context: "Bạn bị lạc trong sân bay và cần hỏi đường.",
      dialog: [
        { speaker: "b", label: "You", en: "Excuse me, could you tell me where gate C15 is?", vi: "Xin lỗi, bạn chỉ cho tôi cửa C15 ở đâu?" },
        { speaker: "a", label: "Staff", en: "Sure! Go straight, then turn left at the duty-free shop. About a 10-minute walk.", vi: "Được! Đi thẳng, rẽ trái tại cửa hàng miễn thuế. Khoảng 10 phút." },
        { speaker: "b", label: "You", en: "Thank you! Is there a shuttle or moving walkway?", vi: "Cảm ơn! Có xe đưa đón hoặc băng chuyền không?" },
        { speaker: "a", label: "Staff", en: "Yes, there's a moving walkway right after the food court.", vi: "Có, có băng chuyền ngay sau khu ẩm thực." },
        { speaker: "b", label: "You", en: "Perfect, thanks a lot!", vi: "Tuyệt vời, cảm ơn nhiều!" },
      ]
    },
    {
      title: "Trên máy bay", icon: "🛩️",
      context: "Bạn đang trên máy bay và cần giao tiếp với tiếp viên.",
      dialog: [
        { speaker: "b", label: "You", en: "Excuse me, could I have some water, please?", vi: "Xin lỗi, tôi có thể xin nước không?" },
        { speaker: "a", label: "Attendant", en: "Of course. Still or sparkling?", vi: "Tất nhiên. Nước lọc hay nước có ga?" },
        { speaker: "b", label: "You", en: "Still water, please. Also, do you have a blanket?", vi: "Nước lọc. Ngoài ra, bạn có chăn không?" },
        { speaker: "a", label: "Attendant", en: "Sure, I'll bring you one right away. Would you like anything else?", vi: "Được, tôi mang cho bạn ngay. Bạn cần gì thêm?" },
        { speaker: "b", label: "You", en: "No, that's all. Thank you very much.", vi: "Không, đủ rồi. Cảm ơn rất nhiều." },
      ]
    },
    {
      title: "Tại xuất nhập cảnh", icon: "🛂",
      context: "Bạn đang qua cửa xuất nhập cảnh khi đến nước ngoài.",
      dialog: [
        { speaker: "a", label: "Officer", en: "Good afternoon. What is the purpose of your visit?", vi: "Chào buổi chiều. Mục đích chuyến đi là gì?" },
        { speaker: "b", label: "You", en: "I'm here on a business trip. I'm visiting our company's office.", vi: "Tôi đến đây công tác. Tôi đến văn phòng công ty." },
        { speaker: "a", label: "Officer", en: "How long will you be staying?", vi: "Bạn sẽ ở bao lâu?" },
        { speaker: "b", label: "You", en: "Two weeks. I'll be leaving on March 28th.", vi: "Hai tuần. Tôi sẽ rời đi ngày 28 tháng 3." },
        { speaker: "a", label: "Officer", en: "Where will you be staying?", vi: "Bạn sẽ ở đâu?" },
        { speaker: "b", label: "You", en: "At the Hilton Hotel, downtown. Here is my hotel reservation.", vi: "Tại khách sạn Hilton, trung tâm. Đây là đặt phòng." },
        { speaker: "a", label: "Officer", en: "Thank you. Welcome and enjoy your stay.", vi: "Cảm ơn. Chào mừng và chúc ở vui." },
      ]
    },
  ],
  phrases: [
    { category: "Check-in & Boarding", items: [
      { en: "I'd like to check in for my flight to...", vi: "Tôi muốn làm thủ tục cho chuyến bay đến...", usage: "Bắt đầu check-in" },
      { en: "Can I have a window/aisle seat, please?", vi: "Tôi có thể chọn ghế cửa sổ/lối đi không?", usage: "Chọn chỗ ngồi" },
      { en: "How much is the baggage allowance?", vi: "Hạn mức hành lý là bao nhiêu?", usage: "Hỏi về hành lý" },
      { en: "Is my flight on time?", vi: "Chuyến bay có đúng giờ không?", usage: "Kiểm tra lịch bay" },
      { en: "Where is the boarding gate?", vi: "Cửa lên máy bay ở đâu?", usage: "Tìm cửa gate" },
      { en: "What time does boarding start?", vi: "Mấy giờ bắt đầu lên máy bay?", usage: "Hỏi giờ boarding" },
      { en: "My luggage is overweight. What should I do?", vi: "Hành lý quá cân. Tôi nên làm gì?", usage: "Quá cân hành lý" },
      { en: "Can I bring this as carry-on?", vi: "Tôi mang cái này lên máy bay được không?", usage: "Hỏi hành lý xách tay" },
    ]},
    { category: "Immigration & Customs", items: [
      { en: "I'm here on a business trip.", vi: "Tôi đến đây công tác.", usage: "Mục đích chuyến đi" },
      { en: "I'll be staying for two weeks.", vi: "Tôi sẽ ở lại hai tuần.", usage: "Thời gian lưu trú" },
      { en: "I'm staying at the Hilton Hotel.", vi: "Tôi ở khách sạn Hilton.", usage: "Nơi lưu trú" },
      { en: "I have nothing to declare.", vi: "Tôi không có gì cần khai báo.", usage: "Qua hải quan" },
      { en: "Here is my invitation letter from the company.", vi: "Đây là thư mời từ công ty.", usage: "Xuất trình giấy tờ" },
      { en: "This is my return ticket.", vi: "Đây là vé khứ hồi của tôi.", usage: "Chứng minh vé về" },
    ]},
    { category: "Tình huống khẩn cấp & Di chuyển", items: [
      { en: "I've lost my luggage. Can you help me?", vi: "Tôi bị mất hành lý. Bạn giúp được không?", usage: "Mất hành lý" },
      { en: "I missed my connecting flight.", vi: "Tôi bị lỡ chuyến bay nối chuyến.", usage: "Lỡ chuyến bay" },
      { en: "Where can I find a taxi / ride service?", vi: "Tôi tìm taxi / dịch vụ đưa đón ở đâu?", usage: "Di chuyển" },
      { en: "Can you book me on the next available flight?", vi: "Bạn đặt cho tôi chuyến bay kế tiếp được không?", usage: "Đổi chuyến bay" },
      { en: "Is there free Wi-Fi at the airport?", vi: "Sân bay có Wi-Fi miễn phí không?", usage: "Kết nối mạng" },
      { en: "Where is the nearest ATM?", vi: "Máy ATM gần nhất ở đâu?", usage: "Rút tiền" },
      { en: "How do I get to the city center from here?", vi: "Tôi đến trung tâm thành phố bằng cách nào?", usage: "Di chuyển vào thành phố" },
    ]},
  ],
};
