// ========== OFFICE DATA (B1 Level) ==========
const OFFICE_DATA = {
  vocabulary: [
    { word: "Meeting room", phonetic: "/ˈmiːtɪŋ ruːm/", meaning: "Phòng họp", example: "The meeting room is on the third floor.", exampleVi: "Phòng họp ở tầng ba." },
    { word: "Deadline", phonetic: "/ˈdɛdlaɪn/", meaning: "Hạn chót", example: "The deadline is next Friday.", exampleVi: "Hạn chót là thứ Sáu tuần sau." },
    { word: "Colleague", phonetic: "/ˈkɒliːɡ/", meaning: "Đồng nghiệp", example: "Let me introduce you to my colleagues.", exampleVi: "Để tôi giới thiệu bạn với đồng nghiệp." },
    { word: "Presentation", phonetic: "/ˌprɛzɛnˈteɪʃn/", meaning: "Bài thuyết trình", example: "I have a presentation at 2 PM.", exampleVi: "Tôi có bài thuyết trình lúc 2 giờ chiều." },
    { word: "Agenda", phonetic: "/əˈdʒɛndə/", meaning: "Chương trình họp", example: "Let's go through the agenda.", exampleVi: "Chúng ta xem qua chương trình họp." },
    { word: "Sprint", phonetic: "/sprɪnt/", meaning: "Sprint (chu kỳ phát triển)", example: "We have a sprint review this afternoon.", exampleVi: "Chiều nay có buổi đánh giá sprint." },
    { word: "Deploy", phonetic: "/dɪˈplɔɪ/", meaning: "Triển khai", example: "We need to deploy the new version by Monday.", exampleVi: "Cần triển khai phiên bản mới trước thứ Hai." },
    { word: "Code review", phonetic: "/koʊd rɪˈvjuː/", meaning: "Đánh giá mã nguồn", example: "Can you do a code review for my pull request?", exampleVi: "Bạn review code cho PR của tôi được không?" },
    { word: "Standup", phonetic: "/ˈstændʌp/", meaning: "Họp đứng hàng ngày", example: "Our daily standup is at 9:15.", exampleVi: "Buổi standup hàng ngày lúc 9:15." },
    { word: "Requirement", phonetic: "/rɪˈkwaɪərmənt/", meaning: "Yêu cầu", example: "Let me clarify the requirements.", exampleVi: "Để tôi làm rõ yêu cầu." },
    { word: "Bug", phonetic: "/bʌɡ/", meaning: "Lỗi phần mềm", example: "We found a critical bug in production.", exampleVi: "Phát hiện lỗi nghiêm trọng trên production." },
    { word: "Stakeholder", phonetic: "/ˈsteɪkhoʊldər/", meaning: "Bên liên quan", example: "We need approval from the stakeholders.", exampleVi: "Cần sự chấp thuận từ các bên liên quan." },
    { word: "Blocker", phonetic: "/ˈblɒkər/", meaning: "Vấn đề chặn tiến độ", example: "Do you have any blockers?", exampleVi: "Bạn có vấn đề chặn tiến độ không?" },
    { word: "Merge", phonetic: "/mɜːrdʒ/", meaning: "Gộp code", example: "Can you merge this branch into develop?", exampleVi: "Bạn merge nhánh này vào develop được không?" },
    { word: "Scope", phonetic: "/skoʊp/", meaning: "Phạm vi", example: "This task is out of scope.", exampleVi: "Task này nằm ngoài phạm vi." },
    { word: "Estimate", phonetic: "/ˈɛstɪmeɪt/", meaning: "Ước lượng", example: "What's your estimate for this task?", exampleVi: "Bạn ước lượng bao lâu cho task này?" },
    { word: "Refactor", phonetic: "/riˈfæktər/", meaning: "Tái cấu trúc code", example: "We need to refactor this module.", exampleVi: "Cần tái cấu trúc module này." },
    { word: "Access", phonetic: "/ˈæksɛs/", meaning: "Quyền truy cập", example: "I don't have access to the repository.", exampleVi: "Tôi không có quyền truy cập repository." },
    // --- B1 Expanded ---
    { word: "Approval", phonetic: "/əˈpruːvl/", meaning: "Sự chấp thuận", example: "I need your approval to proceed.", exampleVi: "Tôi cần sự chấp thuận của bạn để tiếp tục." },
    { word: "Feedback", phonetic: "/ˈfiːdbæk/", meaning: "Phản hồi", example: "Could you give me some feedback on this?", exampleVi: "Bạn cho tôi phản hồi về cái này được không?" },
    { word: "Priority", phonetic: "/praɪˈɒrɪti/", meaning: "Ưu tiên", example: "This is a high-priority task.", exampleVi: "Đây là task ưu tiên cao." },
    { word: "Escalate", phonetic: "/ˈɛskəleɪt/", meaning: "Leo thang, báo cấp trên", example: "We need to escalate this issue.", exampleVi: "Cần báo cấp trên về vấn đề này." },
    { word: "Collaborate", phonetic: "/kəˈlæbəreɪt/", meaning: "Cộng tác", example: "Let's collaborate on this project.", exampleVi: "Mình cùng cộng tác dự án này nhé." },
    { word: "Repository", phonetic: "/rɪˈpɒzɪtɔːri/", meaning: "Kho lưu trữ code", example: "Clone the repository first.", exampleVi: "Clone repository trước." },
    { word: "Branch", phonetic: "/bræntʃ/", meaning: "Nhánh code", example: "Create a new branch for this feature.", exampleVi: "Tạo nhánh mới cho tính năng này." },
    { word: "Pull request", phonetic: "/pʊl rɪˈkwɛst/", meaning: "Yêu cầu gộp code", example: "I've submitted a pull request.", exampleVi: "Tôi đã gửi pull request." },
    { word: "Pipeline", phonetic: "/ˈpaɪplaɪn/", meaning: "Quy trình tự động", example: "The pipeline is running.", exampleVi: "Pipeline đang chạy." },
    { word: "Environment", phonetic: "/ɪnˈvaɪrənmənt/", meaning: "Môi trường", example: "We need to test in the staging environment.", exampleVi: "Cần test trên môi trường staging." },
    { word: "Configuration", phonetic: "/kənˌfɪɡjəˈreɪʃn/", meaning: "Cấu hình", example: "Check the configuration file.", exampleVi: "Kiểm tra file cấu hình." },
    { word: "Database", phonetic: "/ˈdeɪtəbeɪs/", meaning: "Cơ sở dữ liệu", example: "The database needs to be updated.", exampleVi: "Cần cập nhật cơ sở dữ liệu." },
    { word: "Backlog", phonetic: "/ˈbæklɒɡ/", meaning: "Danh sách công việc tồn đọng", example: "Add it to the backlog.", exampleVi: "Thêm vào backlog." },
    { word: "Demo", phonetic: "/ˈdɛmoʊ/", meaning: "Trình diễn", example: "We have a demo for the client tomorrow.", exampleVi: "Ngày mai có demo cho khách hàng." },
    { word: "Milestone", phonetic: "/ˈmaɪlstoʊn/", meaning: "Cột mốc", example: "We've reached an important milestone.", exampleVi: "Chúng ta đã đạt cột mốc quan trọng." },
    { word: "Workload", phonetic: "/ˈwɜːrkloʊd/", meaning: "Khối lượng công việc", example: "My workload is quite heavy this week.", exampleVi: "Khối lượng công việc tuần này khá nặng." },
    { word: "Documentation", phonetic: "/ˌdɒkjəmɛnˈteɪʃn/", meaning: "Tài liệu", example: "We need to update the documentation.", exampleVi: "Cần cập nhật tài liệu." },
    { word: "Architecture", phonetic: "/ˈɑːrkɪtɛktʃər/", meaning: "Kiến trúc", example: "Let's discuss the system architecture.", exampleVi: "Mình thảo luận kiến trúc hệ thống." },
    { word: "Performance", phonetic: "/pərˈfɔːrməns/", meaning: "Hiệu năng", example: "We need to improve the performance.", exampleVi: "Cần cải thiện hiệu năng." },
    { word: "Integration", phonetic: "/ˌɪntɪˈɡreɪʃn/", meaning: "Tích hợp", example: "The API integration is complete.", exampleVi: "Tích hợp API đã hoàn tất." },
    { word: "Dependency", phonetic: "/dɪˈpɛndənsi/", meaning: "Phụ thuộc", example: "We need to update the dependencies.", exampleVi: "Cần cập nhật các dependency." },
    { word: "Credential", phonetic: "/krɪˈdɛnʃl/", meaning: "Thông tin xác thực", example: "Don't share your credentials.", exampleVi: "Đừng chia sẻ thông tin xác thực." },
    { word: "Bandwidth", phonetic: "/ˈbændwɪdθ/", meaning: "Băng thông / Thời gian rảnh", example: "Do you have bandwidth for this task?", exampleVi: "Bạn có thời gian cho task này không?" },
    { word: "Sync up", phonetic: "/sɪŋk ʌp/", meaning: "Đồng bộ, cập nhật nhau", example: "Let's sync up after lunch.", exampleVi: "Mình cập nhật nhau sau bữa trưa nhé." },
    { word: "Follow up", phonetic: "/ˈfɒloʊ ʌp/", meaning: "Theo dõi tiếp", example: "I'll follow up on this issue.", exampleVi: "Tôi sẽ theo dõi tiếp vấn đề này." },
    { word: "Workaround", phonetic: "/ˈwɜːrkəraʊnd/", meaning: "Giải pháp tạm thời", example: "We found a workaround.", exampleVi: "Chúng tôi tìm ra giải pháp tạm thời." },
    { word: "Release", phonetic: "/rɪˈliːs/", meaning: "Phát hành", example: "The release is scheduled for Friday.", exampleVi: "Phát hành được lên lịch vào thứ Sáu." },
    { word: "Rollback", phonetic: "/ˈroʊlbæk/", meaning: "Hoàn tác, quay lại phiên bản cũ", example: "We need to rollback the latest change.", exampleVi: "Cần rollback thay đổi mới nhất." },
    { word: "Debugging", phonetic: "/diːˈbʌɡɪŋ/", meaning: "Gỡ lỗi", example: "I've been debugging this issue all morning.", exampleVi: "Tôi gỡ lỗi cả buổi sáng." },
    { word: "Hotfix", phonetic: "/ˈhɒtfɪks/", meaning: "Sửa lỗi khẩn", example: "We need a hotfix for this bug.", exampleVi: "Cần hotfix cho lỗi này." },
    { word: "Sprint planning", phonetic: "/sprɪnt ˈplænɪŋ/", meaning: "Lên kế hoạch sprint", example: "Sprint planning is on Monday.", exampleVi: "Sprint planning vào thứ Hai." },
    { word: "Retrospective", phonetic: "/ˌrɛtrəˈspɛktɪv/", meaning: "Họp rút kinh nghiệm", example: "What went well in the retrospective?", exampleVi: "Điều gì tốt trong buổi retro?" },
    { word: "User story", phonetic: "/ˈjuːzər ˈstɔːri/", meaning: "Câu chuyện người dùng", example: "Let me explain this user story.", exampleVi: "Để tôi giải thích user story này." },
    { word: "Acceptance criteria", phonetic: "/əkˈsɛptəns kraɪˈtɪəriə/", meaning: "Tiêu chí chấp nhận", example: "Verify the acceptance criteria.", exampleVi: "Kiểm tra tiêu chí chấp nhận." },
    { word: "Onboarding", phonetic: "/ˈɒnbɔːrdɪŋ/", meaning: "Quy trình hội nhập", example: "The onboarding process takes a week.", exampleVi: "Quy trình hội nhập mất một tuần." },
    { word: "Overtime", phonetic: "/ˈoʊvərtaɪm/", meaning: "Làm thêm giờ", example: "We might need to work overtime.", exampleVi: "Có thể cần làm thêm giờ." },
    { word: "Escalation", phonetic: "/ˌɛskəˈleɪʃn/", meaning: "Sự leo thang", example: "This requires an escalation to management.", exampleVi: "Vấn đề cần leo thang lên quản lý." },
    { word: "Proactive", phonetic: "/proʊˈæktɪv/", meaning: "Chủ động", example: "Be proactive in communication.", exampleVi: "Hãy chủ động trong giao tiếp." },
    { word: "Align", phonetic: "/əˈlaɪn/", meaning: "Đồng bộ, thống nhất", example: "Let's align on the approach.", exampleVi: "Mình thống nhất cách tiếp cận nhé." },
    { word: "Capacity", phonetic: "/kəˈpæsɪti/", meaning: "Năng lực, khả năng", example: "We don't have the capacity right now.", exampleVi: "Hiện tại không đủ năng lực." },
    { word: "Handover", phonetic: "/ˈhændoʊvər/", meaning: "Bàn giao", example: "We need a proper handover.", exampleVi: "Cần bàn giao đúng quy trình." },
    { word: "Standup meeting", phonetic: "/ˈstændʌp ˈmiːtɪŋ/", meaning: "Cuộc họp nhanh đứng", example: "Let's keep the standup meeting short.", exampleVi: "Giữ cuộc họp standup ngắn gọn nhé." },
    { word: "Technical debt", phonetic: "/ˈtɛknɪkl dɛt/", meaning: "Nợ kỹ thuật", example: "We should address this technical debt.", exampleVi: "Nên giải quyết nợ kỹ thuật này." },
    { word: "Pair programming", phonetic: "/pɛr ˈproʊɡræmɪŋ/", meaning: "Lập trình theo cặp", example: "Let's do pair programming on this.", exampleVi: "Mình pair programming cái này nhé." },
    { word: "Deployment", phonetic: "/dɪˈplɔɪmənt/", meaning: "Việc triển khai", example: "The deployment went smoothly.", exampleVi: "Việc triển khai diễn ra suôn sẻ." },
    { word: "Incident", phonetic: "/ˈɪnsɪdənt/", meaning: "Sự cố", example: "We had a production incident.", exampleVi: "Có sự cố trên production." },
    { word: "Monitoring", phonetic: "/ˈmɒnɪtərɪŋ/", meaning: "Giám sát", example: "Set up monitoring for the new service.", exampleVi: "Cài đặt giám sát cho service mới." },
    { word: "Bottleneck", phonetic: "/ˈbɒtlnɛk/", meaning: "Nút thắt cổ chai", example: "The database query is a bottleneck.", exampleVi: "Truy vấn database là nút thắt." },
    { word: "Scalable", phonetic: "/ˈskeɪləbl/", meaning: "Có thể mở rộng", example: "We need a scalable solution.", exampleVi: "Cần giải pháp có thể mở rộng." },
    { word: "Migration", phonetic: "/maɪˈɡreɪʃn/", meaning: "Di chuyển (dữ liệu/hệ thống)", example: "Plan the database migration carefully.", exampleVi: "Lên kế hoạch di chuyển database cẩn thận." },
    { word: "Downtime", phonetic: "/ˈdaʊntaɪm/", meaning: "Thời gian ngừng hoạt động", example: "We expect minimal downtime.", exampleVi: "Dự kiến thời gian ngừng tối thiểu." },
    { word: "Ownership", phonetic: "/ˈoʊnərʃɪp/", meaning: "Quyền sở hữu, trách nhiệm", example: "Who has ownership of this module?", exampleVi: "Ai chịu trách nhiệm module này?" },
  ],
  conversations: [
    {
      title: "Giới thiệu bản thân ngày đầu", icon: "👋",
      context: "Ngày đầu tiên đến văn phòng onsite, bạn được giới thiệu với team.",
      dialog: [
        { speaker: "a", label: "Manager", en: "Hi everyone, I'd like you to meet our colleague from Vietnam. He'll be with us for two weeks.", vi: "Chào mọi người, giới thiệu đồng nghiệp từ Việt Nam. Anh ấy ở hai tuần." },
        { speaker: "b", label: "You", en: "Hi, nice to meet you all! My name is [Name]. I'm a software developer from the Hanoi office.", vi: "Xin chào, rất vui! Tôi tên [Name], lập trình viên từ VP Hà Nội." },
        { speaker: "a", label: "Colleague", en: "Welcome! How was your flight?", vi: "Chào mừng! Chuyến bay thế nào?" },
        { speaker: "b", label: "You", en: "It was good, thank you. A bit long but I managed to rest on the plane.", vi: "Tốt, cảm ơn. Hơi dài nhưng tôi nghỉ ngơi được trên máy bay." },
        { speaker: "a", label: "Colleague", en: "Great! If you need anything, don't hesitate to ask. Let me show you around.", vi: "Tuyệt! Cần gì cứ hỏi. Để tôi dẫn bạn xem văn phòng." },
        { speaker: "b", label: "You", en: "That would be great. Thank you so much!", vi: "Tuyệt vời. Cảm ơn rất nhiều!" },
      ]
    },
    {
      title: "Trong buổi họp standup", icon: "📊",
      context: "Bạn tham gia buổi họp standup hàng ngày.",
      dialog: [
        { speaker: "a", label: "SM", en: "Alright, let's start the standup. What did you work on yesterday?", vi: "OK, bắt đầu standup. Hôm qua bạn làm gì?" },
        { speaker: "b", label: "You", en: "Yesterday I finished the API integration for the user module. I also fixed two bugs.", vi: "Hôm qua tôi xong tích hợp API module user. Cũng sửa hai bug." },
        { speaker: "a", label: "SM", en: "Good. What are you planning to do today?", vi: "Tốt. Hôm nay định làm gì?" },
        { speaker: "b", label: "You", en: "Today I'll work on unit tests and start the code review for the payment feature.", vi: "Hôm nay viết unit test và bắt đầu review code tính năng thanh toán." },
        { speaker: "a", label: "SM", en: "Any blockers?", vi: "Có blocker nào không?" },
        { speaker: "b", label: "You", en: "Yes, I need access to the staging database.", vi: "Có, tôi cần quyền truy cập DB staging." },
        { speaker: "a", label: "Colleague", en: "I'll set that up for you after the meeting.", vi: "Tôi setup cho bạn sau họp." },
      ]
    },
    {
      title: "Thảo luận kỹ thuật", icon: "💻",
      context: "Bạn thảo luận vấn đề kỹ thuật với đồng nghiệp.",
      dialog: [
        { speaker: "b", label: "You", en: "Hey, do you have a minute? I'd like to discuss the architecture.", vi: "Này, bạn có phút rảnh không? Muốn thảo luận kiến trúc." },
        { speaker: "a", label: "Colleague", en: "Sure! What's on your mind?", vi: "Được! Bạn đang nghĩ gì?" },
        { speaker: "b", label: "You", en: "I think we should use microservices instead of adding to the monolith.", vi: "Tôi nghĩ nên dùng microservice thay vì thêm vào monolith." },
        { speaker: "a", label: "Colleague", en: "That makes sense. But have you considered the deployment complexity?", vi: "Hợp lý. Nhưng bạn đã xem xét độ phức tạp deploy chưa?" },
        { speaker: "b", label: "You", en: "Yes, I was thinking Docker and Kubernetes. I'll prepare a proposal.", vi: "Rồi, tôi nghĩ dùng Docker và K8s. Tôi sẽ chuẩn bị đề xuất." },
        { speaker: "a", label: "Colleague", en: "Sounds good. Let's bring it up in sprint planning.", vi: "Hay đó. Đưa ra thảo luận trong sprint planning nhé." },
      ]
    },
    {
      title: "Nhờ giúp đỡ về code", icon: "🤝",
      context: "Bạn gặp vấn đề khi code và nhờ đồng nghiệp giúp.",
      dialog: [
        { speaker: "b", label: "You", en: "Hey, could you help me? I'm stuck on a problem.", vi: "Này, giúp tôi được không? Tôi đang bị stuck." },
        { speaker: "a", label: "Colleague", en: "Sure, what seems to be the issue?", vi: "Được, vấn đề là gì?" },
        { speaker: "b", label: "You", en: "I'm getting a null pointer exception when calling this service.", vi: "Tôi bị null pointer khi gọi service này." },
        { speaker: "a", label: "Colleague", en: "Let me look. Ah — you need to inject the dependency here.", vi: "Để tôi xem. À — bạn cần inject dependency ở đây." },
        { speaker: "b", label: "You", en: "Oh, I see! That makes sense now. Thanks a lot!", vi: "À, hiểu rồi! Hợp lý. Cảm ơn nhiều!" },
      ]
    },
    {
      title: "Sprint retrospective", icon: "🔄",
      context: "Cuối sprint, team họp rút kinh nghiệm.",
      dialog: [
        { speaker: "a", label: "SM", en: "Let's start the retro. What went well this sprint?", vi: "Bắt đầu retro nào. Sprint này có gì tốt?" },
        { speaker: "b", label: "You", en: "I think the collaboration between our teams was really effective.", vi: "Tôi nghĩ sự phối hợp giữa các team rất hiệu quả." },
        { speaker: "a", label: "SM", en: "Agreed. Anything that could be improved?", vi: "Đồng ý. Có gì cần cải thiện?" },
        { speaker: "b", label: "You", en: "I think we could improve our testing process. We had some bugs that slipped through.", vi: "Tôi nghĩ nên cải thiện quy trình testing. Có vài bug bị lọt." },
        { speaker: "a", label: "Colleague", en: "Good point. We should add more integration tests.", vi: "Ý hay. Nên thêm integration tests." },
      ]
    },
  ],
  phrases: [
    { category: "Giới thiệu & Chào hỏi", items: [
      { en: "Nice to meet you. I'm [Name] from the Vietnam team.", vi: "Rất vui. Tôi là [Name] từ team Việt Nam.", usage: "Ngày đầu gặp mặt" },
      { en: "I'll be working with you for the next two weeks.", vi: "Tôi sẽ làm việc với bạn hai tuần tới.", usage: "Tự giới thiệu" },
      { en: "Could you show me where the restroom is?", vi: "Chỉ tôi nhà vệ sinh ở đâu?", usage: "Hỏi trong VP" },
      { en: "What's the Wi-Fi password?", vi: "Mật khẩu Wi-Fi là gì?", usage: "Kết nối mạng" },
      { en: "Where can I sit?", vi: "Tôi ngồi đâu?", usage: "Ngày đầu" },
      { en: "What time does the office open/close?", vi: "Văn phòng mở/đóng cửa mấy giờ?", usage: "Giờ làm việc" },
    ]},
    { category: "Trong cuộc họp", items: [
      { en: "Could you repeat that, please?", vi: "Bạn lặp lại được không?", usage: "Khi không nghe rõ" },
      { en: "I have a question about this topic.", vi: "Tôi có câu hỏi về chủ đề này.", usage: "Đặt câu hỏi" },
      { en: "I agree with your point.", vi: "Tôi đồng ý với ý kiến bạn.", usage: "Đồng ý" },
      { en: "I think we should consider another approach.", vi: "Nên cân nhắc cách tiếp cận khác.", usage: "Đề xuất" },
      { en: "Let me share my screen.", vi: "Để tôi chia sẻ màn hình.", usage: "Trình bày" },
      { en: "Can we schedule a follow-up meeting?", vi: "Lên lịch họp tiếp được không?", usage: "Đặt lịch" },
      { en: "Sorry, could you slow down a bit?", vi: "Xin lỗi, bạn nói chậm hơn được không?", usage: "Khi nghe không kịp" },
      { en: "Can you elaborate on that?", vi: "Bạn có thể giải thích thêm không?", usage: "Cần thêm thông tin" },
    ]},
    { category: "Công việc hàng ngày", items: [
      { en: "I'll push my changes to the branch.", vi: "Tôi sẽ push code lên nhánh.", usage: "Git" },
      { en: "The build is failing. Can you check?", vi: "Build đang fail. Bạn check được không?", usage: "Debug" },
      { en: "I need more context on this ticket.", vi: "Tôi cần thêm thông tin về ticket này.", usage: "Requirement" },
      { en: "Let's pair-program on this issue.", vi: "Mình pair-program cái này nhé.", usage: "Teamwork" },
      { en: "I'll update the Jira board.", vi: "Tôi sẽ cập nhật Jira.", usage: "Project mgmt" },
      { en: "Could you review my pull request?", vi: "Bạn review PR của tôi được không?", usage: "Code review" },
      { en: "I'm working on it. Should be done by EOD.", vi: "Tôi đang làm. Xong trước cuối ngày.", usage: "Cập nhật tiến độ" },
      { en: "This is blocked by a dependency.", vi: "Cái này đang bị block bởi dependency.", usage: "Báo blocker" },
    ]},
  ],
};
