// ========== CANTEEN DATA (B1 Level) ==========
const CANTEEN_DATA = {
  vocabulary: [
    { word: "Menu", phonetic: "/ˈmɛnjuː/", meaning: "Thực đơn", example: "Can I see the menu, please?", exampleVi: "Tôi xem thực đơn được không?" },
    { word: "Vegetarian", phonetic: "/ˌvɛdʒɪˈtɛriən/", meaning: "Ăn chay", example: "Do you have any vegetarian options?", exampleVi: "Có món chay nào không?" },
    { word: "Allergic", phonetic: "/əˈlɜːrdʒɪk/", meaning: "Dị ứng", example: "I'm allergic to peanuts.", exampleVi: "Tôi dị ứng đậu phộng." },
    { word: "Spicy", phonetic: "/ˈspaɪsi/", meaning: "Cay", example: "Is this dish spicy?", exampleVi: "Món này có cay không?" },
    { word: "Appetizer", phonetic: "/ˈæpɪtaɪzər/", meaning: "Món khai vị", example: "Would you like an appetizer?", exampleVi: "Bạn muốn khai vị không?" },
    { word: "Main course", phonetic: "/meɪn kɔːrs/", meaning: "Món chính", example: "What would you like for your main course?", exampleVi: "Bạn muốn gì cho món chính?" },
    { word: "Beverage", phonetic: "/ˈbɛvərɪdʒ/", meaning: "Đồ uống", example: "What beverages do you have?", exampleVi: "Bạn có đồ uống gì?" },
    { word: "Bill", phonetic: "/bɪl/", meaning: "Hóa đơn", example: "Can I have the bill, please?", exampleVi: "Cho tôi xin hóa đơn." },
    { word: "Tip", phonetic: "/tɪp/", meaning: "Tiền boa", example: "How much should I tip?", exampleVi: "Tôi nên tip bao nhiêu?" },
    { word: "Portion", phonetic: "/ˈpɔːrʃn/", meaning: "Phần ăn", example: "The portions are quite large.", exampleVi: "Phần ăn khá lớn." },
    { word: "Side dish", phonetic: "/saɪd dɪʃ/", meaning: "Món ăn kèm", example: "What side dishes do you recommend?", exampleVi: "Bạn đề xuất món ăn kèm nào?" },
    { word: "Dessert", phonetic: "/dɪˈzɜːrt/", meaning: "Tráng miệng", example: "Do you want dessert?", exampleVi: "Bạn muốn tráng miệng không?" },
    { word: "Takeaway", phonetic: "/ˈteɪkəweɪ/", meaning: "Mang đi", example: "Is this for here or takeaway?", exampleVi: "Ăn tại đây hay mang đi?" },
    { word: "Gluten-free", phonetic: "/ˈɡluːtn friː/", meaning: "Không chứa gluten", example: "Do you have gluten-free options?", exampleVi: "Có lựa chọn không gluten không?" },
    { word: "Refill", phonetic: "/ˈriːfɪl/", meaning: "Rót thêm", example: "Can I get a refill on my coffee?", exampleVi: "Tôi rót thêm cà phê được không?" },
    { word: "Microwave", phonetic: "/ˈmaɪkrəweɪv/", meaning: "Lò vi sóng", example: "Where is the microwave?", exampleVi: "Lò vi sóng ở đâu?" },
    // --- B1 Expanded ---
    { word: "Cutlery", phonetic: "/ˈkʌtləri/", meaning: "Bộ dao dĩa", example: "Where can I find the cutlery?", exampleVi: "Tôi tìm bộ dao dĩa ở đâu?" },
    { word: "Napkin", phonetic: "/ˈnæpkɪn/", meaning: "Khăn giấy", example: "Could I have some more napkins?", exampleVi: "Cho tôi thêm khăn giấy?" },
    { word: "Salad", phonetic: "/ˈsæləd/", meaning: "Rau trộn", example: "I'll have a Caesar salad.", exampleVi: "Tôi lấy salad Caesar." },
    { word: "Grilled", phonetic: "/ɡrɪld/", meaning: "Nướng", example: "I'd like the grilled chicken.", exampleVi: "Tôi muốn gà nướng." },
    { word: "Fried", phonetic: "/fraɪd/", meaning: "Chiên", example: "Do you have fried rice?", exampleVi: "Bạn có cơm chiên không?" },
    { word: "Steamed", phonetic: "/stiːmd/", meaning: "Hấp", example: "The steamed vegetables are healthy.", exampleVi: "Rau hấp rất tốt cho sức khỏe." },
    { word: "Roasted", phonetic: "/ˈroʊstɪd/", meaning: "Nướng (lò)", example: "Try the roasted potatoes.", exampleVi: "Thử khoai tây nướng lò." },
    { word: "Sauce", phonetic: "/sɔːs/", meaning: "Nước sốt", example: "What kind of sauce is this?", exampleVi: "Đây là loại sốt gì?" },
    { word: "Dressing", phonetic: "/ˈdrɛsɪŋ/", meaning: "Nước trộn salad", example: "I'd like vinaigrette dressing.", exampleVi: "Tôi muốn nước trộn vinaigrette." },
    { word: "Seasoning", phonetic: "/ˈsiːzənɪŋ/", meaning: "Gia vị", example: "Can I add some seasoning?", exampleVi: "Tôi thêm gia vị được không?" },
    { word: "Sparkling water", phonetic: "/ˈspɑːrklɪŋ ˈwɔːtər/", meaning: "Nước có ga", example: "I'd like a sparkling water.", exampleVi: "Tôi muốn nước có ga." },
    { word: "Still water", phonetic: "/stɪl ˈwɔːtər/", meaning: "Nước lọc", example: "Just still water for me.", exampleVi: "Cho tôi nước lọc thôi." },
    { word: "Cappuccino", phonetic: "/ˌkæpuˈtʃiːnoʊ/", meaning: "Cà phê cappuccino", example: "I'll have a cappuccino after lunch.", exampleVi: "Tôi uống cappuccino sau bữa trưa." },
    { word: "Espresso", phonetic: "/ɛˈsprɛsoʊ/", meaning: "Cà phê espresso", example: "A double espresso, please.", exampleVi: "Cho tôi espresso đôi." },
    { word: "Latte", phonetic: "/ˈlɑːteɪ/", meaning: "Cà phê latte", example: "Can I have an oat milk latte?", exampleVi: "Cho tôi latte sữa yến mạch?" },
    { word: "Leftovers", phonetic: "/ˈlɛftoʊvərz/", meaning: "Đồ ăn thừa", example: "Can I take the leftovers?", exampleVi: "Tôi mang đồ thừa đi được không?" },
    { word: "Snack", phonetic: "/snæk/", meaning: "Đồ ăn nhẹ", example: "There are snacks in the kitchen.", exampleVi: "Có đồ ăn nhẹ trong bếp." },
    { word: "Vending machine", phonetic: "/ˈvɛndɪŋ məˈʃiːn/", meaning: "Máy bán tự động", example: "Get a drink from the vending machine.", exampleVi: "Lấy nước từ máy bán tự động." },
    { word: "Water dispenser", phonetic: "/ˈwɔːtər dɪˈspɛnsər/", meaning: "Máy lấy nước", example: "The water dispenser is next to the fridge.", exampleVi: "Máy lấy nước cạnh tủ lạnh." },
    { word: "Fridge", phonetic: "/frɪdʒ/", meaning: "Tủ lạnh", example: "You can store your food in the fridge.", exampleVi: "Bạn có thể để đồ ăn trong tủ lạnh." },
    { word: "Kettle", phonetic: "/ˈkɛtl/", meaning: "Ấm đun nước", example: "Boil some water in the kettle.", exampleVi: "Đun nước trong ấm." },
    { word: "Plate", phonetic: "/pleɪt/", meaning: "Đĩa", example: "Can I have a clean plate?", exampleVi: "Cho tôi đĩa sạch?" },
    { word: "Bowl", phonetic: "/boʊl/", meaning: "Bát, tô", example: "I need a bowl for the soup.", exampleVi: "Tôi cần bát để đựng súp." },
    { word: "Glass", phonetic: "/ɡlæs/", meaning: "Ly, cốc thủy tinh", example: "Can I have a glass of water?", exampleVi: "Cho tôi một ly nước?" },
    { word: "Mug", phonetic: "/mʌɡ/", meaning: "Cốc có quai", example: "Where are the coffee mugs?", exampleVi: "Cốc cà phê ở đâu?" },
    { word: "Straw", phonetic: "/strɔː/", meaning: "Ống hút", example: "Do you have paper straws?", exampleVi: "Bạn có ống hút giấy không?" },
    { word: "Tray", phonetic: "/treɪ/", meaning: "Khay", example: "Put your food on a tray.", exampleVi: "Đặt đồ ăn lên khay." },
    { word: "Soup", phonetic: "/suːp/", meaning: "Súp", example: "Today's soup is tomato.", exampleVi: "Súp hôm nay là cà chua." },
    { word: "Sandwich", phonetic: "/ˈsændwɪtʃ/", meaning: "Bánh mì kẹp", example: "I'll grab a sandwich for lunch.", exampleVi: "Tôi lấy bánh mì kẹp cho bữa trưa." },
    { word: "Pasta", phonetic: "/ˈpæstə/", meaning: "Mì Ý", example: "The pasta is really good here.", exampleVi: "Mì Ý ở đây rất ngon." },
    { word: "Steak", phonetic: "/steɪk/", meaning: "Bít tết", example: "How would you like your steak?", exampleVi: "Bạn muốn bít tết chín mức nào?" },
    { word: "Well-done", phonetic: "/wɛl dʌn/", meaning: "Chín kỹ", example: "I'd like my steak well-done.", exampleVi: "Tôi muốn bít tết chín kỹ." },
    { word: "Medium rare", phonetic: "/ˈmiːdiəm rɛr/", meaning: "Tái vừa", example: "Medium rare for me, please.", exampleVi: "Cho tôi tái vừa." },
    { word: "Dairy", phonetic: "/ˈdɛri/", meaning: "Sản phẩm từ sữa", example: "I'm avoiding dairy.", exampleVi: "Tôi đang tránh sản phẩm sữa." },
    { word: "Ingredient", phonetic: "/ɪnˈɡriːdiənt/", meaning: "Thành phần, nguyên liệu", example: "What are the main ingredients?", exampleVi: "Thành phần chính là gì?" },
    { word: "Reservation", phonetic: "/ˌrɛzərˈveɪʃn/", meaning: "Đặt bàn", example: "I have a reservation for two.", exampleVi: "Tôi có đặt bàn cho hai người." },
    { word: "Waiter", phonetic: "/ˈweɪtər/", meaning: "Bồi bàn (nam)", example: "Excuse me, waiter!", exampleVi: "Xin lỗi, bồi bàn!" },
    { word: "Waitress", phonetic: "/ˈweɪtrəs/", meaning: "Bồi bàn (nữ)", example: "The waitress will take your order.", exampleVi: "Nhân viên sẽ ghi order cho bạn." },
    { word: "Special", phonetic: "/ˈspɛʃl/", meaning: "Đặc biệt (món đặc biệt)", example: "What's the daily special?", exampleVi: "Món đặc biệt hôm nay là gì?" },
    { word: "Buffet", phonetic: "/bʊˈfeɪ/", meaning: "Tiệc buffet", example: "There's a buffet on Fridays.", exampleVi: "Thứ Sáu có tiệc buffet." },
    { word: "Counter", phonetic: "/ˈkaʊntər/", meaning: "Quầy", example: "Order at the counter.", exampleVi: "Gọi món tại quầy." },
    { word: "Utensils", phonetic: "/juːˈtɛnslz/", meaning: "Dụng cụ ăn", example: "The utensils are on the table.", exampleVi: "Dụng cụ ăn trên bàn." },
    { word: "Bland", phonetic: "/blænd/", meaning: "Nhạt", example: "This soup is a bit bland.", exampleVi: "Súp này hơi nhạt." },
    { word: "Delicious", phonetic: "/dɪˈlɪʃəs/", meaning: "Ngon", example: "This is really delicious!", exampleVi: "Cái này thật sự ngon!" },
    { word: "Crispy", phonetic: "/ˈkrɪspi/", meaning: "Giòn", example: "The chicken is nice and crispy.", exampleVi: "Gà giòn ngon." },
    { word: "Tender", phonetic: "/ˈtɛndər/", meaning: "Mềm, mọng nước", example: "The meat is very tender.", exampleVi: "Thịt rất mềm." },
    { word: "Coffee machine", phonetic: "/ˈkɒfi məˈʃiːn/", meaning: "Máy pha cà phê", example: "The coffee machine is in the kitchen.", exampleVi: "Máy pha cà phê trong bếp." },
  ],
  conversations: [
    {
      title: "Gọi món tại căn tin", icon: "🍽️",
      context: "Bạn đang ở căn tin công ty và muốn gọi món ăn trưa.",
      dialog: [
        { speaker: "b", label: "You", en: "Hi! What do you recommend for lunch today?", vi: "Xin chào! Hôm nay giới thiệu gì cho bữa trưa?" },
        { speaker: "a", label: "Staff", en: "Today's special is grilled chicken with roasted vegetables. We also have pasta and soup.", vi: "Món đặc biệt hôm nay là gà nướng với rau nướng. Cũng có mì Ý và súp." },
        { speaker: "b", label: "You", en: "The grilled chicken sounds good. Is it spicy?", vi: "Gà nướng nghe hay. Có cay không?" },
        { speaker: "a", label: "Staff", en: "No, it's not spicy. We can add chili sauce on the side.", vi: "Không cay. Có thể thêm tương ớt bên cạnh." },
        { speaker: "b", label: "You", en: "Perfect, I'll have that. And a glass of orange juice.", vi: "Hoàn hảo, tôi lấy món đó. Và một ly nước cam." },
        { speaker: "a", label: "Staff", en: "Sure! Ready in about five minutes.", vi: "Được! Khoảng năm phút nữa xong." },
      ]
    },
    {
      title: "Ăn trưa với đồng nghiệp", icon: "🤗",
      context: "Bạn ăn trưa cùng đồng nghiệp và trò chuyện xã giao.",
      dialog: [
        { speaker: "a", label: "Colleague", en: "Hey, mind if I join you for lunch?", vi: "Này, tôi ngồi ăn cùng được không?" },
        { speaker: "b", label: "You", en: "Of course! Please sit down. How's your day?", vi: "Tất nhiên! Ngồi đi. Ngày hôm nay thế nào?" },
        { speaker: "a", label: "Colleague", en: "Pretty busy. Back-to-back meetings this morning. How are you settling in?", vi: "Khá bận. Sáng nay họp liên tục. Bạn ổn định chưa?" },
        { speaker: "b", label: "You", en: "I'm getting used to it. The food here is good!", vi: "Tôi đang quen dần. Đồ ăn ở đây ngon!" },
        { speaker: "a", label: "Colleague", en: "Have you tried the coffee machine? It makes amazing cappuccinos.", vi: "Bạn thử máy cà phê chưa? Cappuccino tuyệt lắm." },
        { speaker: "b", label: "You", en: "Not yet! I'll try it after lunch. Thanks!", vi: "Chưa! Tôi sẽ thử sau bữa trưa. Cảm ơn!" },
      ]
    },
    {
      title: "Hỏi về dị ứng thực phẩm", icon: "🥗",
      context: "Bạn cần hỏi về thực phẩm phù hợp vì dị ứng.",
      dialog: [
        { speaker: "b", label: "You", en: "Excuse me, I have a food allergy. Does this contain nuts?", vi: "Xin lỗi, tôi bị dị ứng. Món này có hạt không?" },
        { speaker: "a", label: "Staff", en: "Let me check. Yes, the sauce contains cashew nuts. Would you like an alternative?", vi: "Để tôi kiểm tra. Vâng, sốt có hạt điều. Bạn muốn thay thế?" },
        { speaker: "b", label: "You", en: "Yes, please. What do you have that's nut-free?", vi: "Vâng. Bạn có gì không chứa hạt?" },
        { speaker: "a", label: "Staff", en: "We have grilled fish with lemon sauce. Completely nut-free.", vi: "Có cá nướng sốt chanh. Hoàn toàn không có hạt." },
        { speaker: "b", label: "You", en: "That sounds perfect. I'll have that, thank you.", vi: "Nghe hoàn hảo. Tôi lấy món đó, cảm ơn." },
      ]
    },
    {
      title: "Mời đồng nghiệp đi ăn", icon: "😄",
      context: "Bạn muốn mời đồng nghiệp đi ăn trưa cùng.",
      dialog: [
        { speaker: "b", label: "You", en: "Hey, would you like to grab lunch together?", vi: "Này, đi ăn trưa cùng không?" },
        { speaker: "a", label: "Colleague", en: "Sure! Are you thinking of the Italian place around the corner?", vi: "Chắc chắn! Bạn đang nghĩ đến quán Ý góc đường?" },
        { speaker: "b", label: "You", en: "Yes! Let me treat you. You've been so helpful.", vi: "Đúng vậy! Để tôi mời. Bạn giúp tôi nhiều rồi." },
        { speaker: "a", label: "Colleague", en: "That's so kind! Let's go at 12:30?", vi: "Bạn tốt quá! Đi lúc 12:30?" },
        { speaker: "b", label: "You", en: "Sounds great! See you in the lobby.", vi: "Tuyệt! Hẹn gặp ở sảnh." },
      ]
    },
    {
      title: "Tại nhà hàng bên ngoài", icon: "🍷",
      context: "Team đi ăn tối tại nhà hàng sau giờ làm.",
      dialog: [
        { speaker: "a", label: "Colleague", en: "Have you decided what you'd like to order?", vi: "Bạn quyết định gọi gì chưa?" },
        { speaker: "b", label: "You", en: "I'm not sure yet. What do you recommend?", vi: "Tôi chưa chắc. Bạn giới thiệu gì?" },
        { speaker: "a", label: "Colleague", en: "The steak here is excellent. How do you like it cooked?", vi: "Bít tết ở đây tuyệt vời. Bạn muốn chín mức nào?" },
        { speaker: "b", label: "You", en: "Medium rare, please. And I'll have a sparkling water to drink.", vi: "Tái vừa. Và cho tôi nước có ga." },
        { speaker: "a", label: "Waiter", en: "Would you like any dessert after your meal?", vi: "Bạn muốn tráng miệng sau bữa ăn không?" },
        { speaker: "b", label: "You", en: "Maybe later. Can we see the dessert menu when we're ready?", vi: "Có lẽ lát nữa. Khi nào sẵn sàng xem menu tráng miệng?" },
        { speaker: "a", label: "Waiter", en: "Of course! Take your time.", vi: "Tất nhiên! Cứ từ từ." },
      ]
    },
  ],
  phrases: [
    { category: "Gọi món & Hỏi thông tin", items: [
      { en: "What's today's special?", vi: "Món đặc biệt hôm nay là gì?", usage: "Hỏi món đặc biệt" },
      { en: "I'd like to order the...", vi: "Tôi muốn gọi món...", usage: "Gọi món ăn" },
      { en: "Does this contain dairy/gluten/nuts?", vi: "Món này có sữa/gluten/hạt không?", usage: "Hỏi thành phần" },
      { en: "Can I have this without onions?", vi: "Lấy món này không hành được không?", usage: "Yêu cầu đặc biệt" },
      { en: "Is this dish served hot or cold?", vi: "Món này nóng hay nguội?", usage: "Hỏi về món ăn" },
      { en: "How long will it take?", vi: "Mất bao lâu?", usage: "Hỏi thời gian chờ" },
      { en: "Can I have the same as him/her?", vi: "Cho tôi giống anh/chị ấy?", usage: "Gọi món dễ dàng" },
      { en: "Is this enough for two people?", vi: "Cái này đủ cho hai người không?", usage: "Hỏi phần ăn" },
    ]},
    { category: "Giao tiếp xã giao khi ăn", items: [
      { en: "Mind if I sit here?", vi: "Tôi ngồi đây được không?", usage: "Xin phép ngồi" },
      { en: "How do you like the food here?", vi: "Bạn thấy đồ ăn ở đây thế nào?", usage: "Small talk" },
      { en: "Have you tried the [dish]? It's really good!", vi: "Bạn thử [món] chưa? Ngon lắm!", usage: "Giới thiệu món" },
      { en: "What do you usually have for lunch?", vi: "Bạn thường ăn gì cho bữa trưa?", usage: "Small talk" },
      { en: "Would you like some coffee after lunch?", vi: "Bạn muốn cà phê sau bữa trưa không?", usage: "Mời đồ uống" },
      { en: "This tastes amazing!", vi: "Cái này ngon tuyệt!", usage: "Khen đồ ăn" },
      { en: "I'm quite full already.", vi: "Tôi khá no rồi.", usage: "Khi đã no" },
      { en: "Do you know any good restaurants around here?", vi: "Bạn biết nhà hàng ngon nào gần đây không?", usage: "Hỏi gợi ý" },
    ]},
    { category: "Thanh toán & Tiện ích", items: [
      { en: "How much is the lunch set?", vi: "Bữa trưa set bao nhiêu?", usage: "Hỏi giá" },
      { en: "Do you accept credit cards?", vi: "Nhận thẻ tín dụng không?", usage: "Thanh toán" },
      { en: "Can I get a receipt, please?", vi: "Cho tôi hóa đơn?", usage: "Lấy hóa đơn" },
      { en: "Where can I get a fork/knife/napkin?", vi: "Lấy nĩa/dao/khăn giấy ở đâu?", usage: "Dụng cụ ăn" },
      { en: "Is there a water dispenser nearby?", vi: "Có máy lấy nước gần đây không?", usage: "Tìm nước" },
      { en: "Can I use the microwave?", vi: "Tôi dùng lò vi sóng được không?", usage: "Hâm nóng đồ ăn" },
      { en: "Let me get this. It's my treat!", vi: "Để tôi trả. Tôi mời!", usage: "Mời trả tiền" },
      { en: "Let's split the bill.", vi: "Mình chia bill nhé.", usage: "Chia hóa đơn" },
    ]},
  ],
};
