// ========== DAILY LIFE DATA (B1 Level) ==========
const DAILY_DATA = {
  vocabulary: [
    { word: "Greet", phonetic: "/ɡriːt/", meaning: "Chào hỏi", example: "He greeted me with a warm smile.", exampleVi: "Anh ấy chào tôi bằng nụ cười ấm áp." },
    { word: "Introduce", phonetic: "/ˌɪntrəˈdjuːs/", meaning: "Giới thiệu", example: "Let me introduce myself.", exampleVi: "Để tôi tự giới thiệu." },
    { word: "Direction", phonetic: "/dɪˈrɛkʃn/", meaning: "Hướng, phương hướng", example: "Can you give me directions to the station?", exampleVi: "Bạn chỉ đường đến ga được không?" },
    { word: "Appointment", phonetic: "/əˈpɔɪntmənt/", meaning: "Cuộc hẹn", example: "I have a doctor's appointment at 3 PM.", exampleVi: "Tôi có hẹn bác sĩ lúc 3 giờ chiều." },
    { word: "Grocery", phonetic: "/ˈɡroʊsəri/", meaning: "Tạp hóa, đồ ăn", example: "I need to buy some groceries.", exampleVi: "Tôi cần mua đồ tạp hóa." },
    { word: "Receipt", phonetic: "/rɪˈsiːt/", meaning: "Hóa đơn, biên lai", example: "Can I have the receipt, please?", exampleVi: "Cho tôi xin biên lai?" },
    { word: "Change", phonetic: "/tʃeɪndʒ/", meaning: "Tiền thối", example: "Here is your change.", exampleVi: "Đây là tiền thối của bạn." },
    { word: "Weather", phonetic: "/ˈwɛðər/", meaning: "Thời tiết", example: "What's the weather like today?", exampleVi: "Thời tiết hôm nay thế nào?" },
    { word: "Temperature", phonetic: "/ˈtɛmpərətʃər/", meaning: "Nhiệt độ", example: "The temperature is very low today.", exampleVi: "Nhiệt độ hôm nay rất thấp." },
    { word: "Pharmacy", phonetic: "/ˈfɑːrməsi/", meaning: "Nhà thuốc", example: "Is there a pharmacy nearby?", exampleVi: "Có nhà thuốc gần đây không?" },
    { word: "Subway", phonetic: "/ˈsʌbweɪ/", meaning: "Tàu điện ngầm", example: "Take the subway to the city center.", exampleVi: "Đi tàu điện ngầm đến trung tâm." },
    { word: "Platform", phonetic: "/ˈplætfɔːrm/", meaning: "Sân ga", example: "The train departs from platform 3.", exampleVi: "Tàu khởi hành từ sân ga số 3." },
    { word: "Pedestrian", phonetic: "/pəˈdɛstriən/", meaning: "Người đi bộ", example: "Use the pedestrian crossing.", exampleVi: "Dùng đường dành cho người đi bộ." },
    { word: "Intersection", phonetic: "/ˌɪntərˈsɛkʃn/", meaning: "Ngã tư", example: "Turn left at the intersection.", exampleVi: "Rẽ trái tại ngã tư." },
    { word: "Accommodation", phonetic: "/əˌkɒməˈdeɪʃn/", meaning: "Chỗ ở", example: "Have you booked your accommodation?", exampleVi: "Bạn đã đặt chỗ ở chưa?" },
    { word: "Check out", phonetic: "/tʃɛk aʊt/", meaning: "Trả phòng", example: "I'd like to check out, please.", exampleVi: "Tôi muốn trả phòng." },
    { word: "Room key", phonetic: "/ruːm kiː/", meaning: "Chìa khóa phòng", example: "I lost my room key.", exampleVi: "Tôi mất chìa khóa phòng." },
    { word: "Laundry", phonetic: "/ˈlɔːndri/", meaning: "Giặt ủi", example: "Where is the laundry service?", exampleVi: "Dịch vụ giặt ủi ở đâu?" },
    { word: "Emergency", phonetic: "/ɪˈmɜːrdʒənsi/", meaning: "Khẩn cấp", example: "Call 911 in case of an emergency.", exampleVi: "Gọi 911 trong trường hợp khẩn cấp." },
    { word: "Headache", phonetic: "/ˈhɛdeɪk/", meaning: "Đau đầu", example: "I have a terrible headache.", exampleVi: "Tôi đau đầu kinh khủng." },
    { word: "Medicine", phonetic: "/ˈmɛdɪsɪn/", meaning: "Thuốc", example: "Do you have any medicine for a cold?", exampleVi: "Bạn có thuốc cảm lạnh không?" },
    { word: "Crosswalk", phonetic: "/ˈkrɒswɔːk/", meaning: "Vạch sang đường", example: "Always use the crosswalk.", exampleVi: "Luôn dùng vạch sang đường." },
    { word: "Roundabout", phonetic: "/ˈraʊndəbaʊt/", meaning: "Bùng binh", example: "Go around the roundabout.", exampleVi: "Đi vòng qua bùng binh." },
    { word: "Convenient", phonetic: "/kənˈviːniənt/", meaning: "Tiện lợi", example: "This location is very convenient.", exampleVi: "Vị trí này rất tiện lợi." },
    { word: "Comfortable", phonetic: "/ˈkʌmftəbl/", meaning: "Thoải mái", example: "The hotel room is very comfortable.", exampleVi: "Phòng khách sạn rất thoải mái." },
    { word: "Umbrella", phonetic: "/ʌmˈbrɛlə/", meaning: "Ô, dù", example: "Don't forget your umbrella, it's raining.", exampleVi: "Đừng quên ô, trời đang mưa." },
    { word: "Jacket", phonetic: "/ˈdʒækɪt/", meaning: "Áo khoác", example: "Bring a jacket, it's cold outside.", exampleVi: "Mang áo khoác, ngoài trời lạnh." },
    { word: "Cash", phonetic: "/kæʃ/", meaning: "Tiền mặt", example: "Do you accept cash?", exampleVi: "Bạn nhận tiền mặt không?" },
    { word: "Credit card", phonetic: "/ˈkrɛdɪt kɑːrd/", meaning: "Thẻ tín dụng", example: "Can I pay by credit card?", exampleVi: "Tôi trả bằng thẻ tín dụng được không?" },
    { word: "ATM", phonetic: "/ˌeɪ tiː ˈɛm/", meaning: "Máy rút tiền", example: "Where is the nearest ATM?", exampleVi: "Máy ATM gần nhất ở đâu?" },
    { word: "Exchange rate", phonetic: "/ɪksˈtʃeɪndʒ reɪt/", meaning: "Tỷ giá hối đoái", example: "What's the exchange rate today?", exampleVi: "Tỷ giá hôm nay bao nhiêu?" },
    { word: "Forecast", phonetic: "/ˈfɔːrkæst/", meaning: "Dự báo", example: "The forecast says it will rain tomorrow.", exampleVi: "Dự báo nói ngày mai sẽ mưa." },
    { word: "Public transport", phonetic: "/ˈpʌblɪk ˈtrænspɔːrt/", meaning: "Phương tiện công cộng", example: "Public transport is very efficient here.", exampleVi: "Giao thông công cộng ở đây rất hiệu quả." },
    { word: "Rush hour", phonetic: "/rʌʃ ˈaʊər/", meaning: "Giờ cao điểm", example: "Avoid travelling during rush hour.", exampleVi: "Tránh đi lại giờ cao điểm." },
    { word: "One-way ticket", phonetic: "/wʌn weɪ ˈtɪkɪt/", meaning: "Vé một chiều", example: "I need a one-way ticket to downtown.", exampleVi: "Tôi cần vé một chiều đi trung tâm." },
    { word: "Return ticket", phonetic: "/rɪˈtɜːrn ˈtɪkɪt/", meaning: "Vé khứ hồi", example: "A return ticket is cheaper.", exampleVi: "Vé khứ hồi rẻ hơn." },
    { word: "Landmark", phonetic: "/ˈlændmɑːrk/", meaning: "Địa danh nổi bật", example: "The tower is a famous landmark.", exampleVi: "Tháp là địa danh nổi tiếng." },
    { word: "Souvenir", phonetic: "/ˌsuːvəˈnɪr/", meaning: "Quà lưu niệm", example: "I want to buy some souvenirs.", exampleVi: "Tôi muốn mua quà lưu niệm." },
    { word: "Discount", phonetic: "/ˈdɪskaʊnt/", meaning: "Giảm giá", example: "Is there a discount for students?", exampleVi: "Có giảm giá cho sinh viên không?" },
    { word: "Queue", phonetic: "/kjuː/", meaning: "Hàng đợi", example: "Please wait in the queue.", exampleVi: "Vui lòng chờ trong hàng." },
    { word: "Excuse me", phonetic: "/ɪkˈskjuːz miː/", meaning: "Xin lỗi (cho phép)", example: "Excuse me, is this seat taken?", exampleVi: "Xin lỗi, chỗ này có ai ngồi không?" },
    { word: "Apology", phonetic: "/əˈpɒlədʒi/", meaning: "Lời xin lỗi", example: "I owe you an apology.", exampleVi: "Tôi nợ bạn lời xin lỗi." },
    { word: "Grateful", phonetic: "/ˈɡreɪtfl/", meaning: "Biết ơn", example: "I'm really grateful for your help.", exampleVi: "Tôi rất biết ơn sự giúp đỡ của bạn." },
    { word: "Polite", phonetic: "/pəˈlaɪt/", meaning: "Lịch sự", example: "He is very polite.", exampleVi: "Anh ấy rất lịch sự." },
    { word: "Homesick", phonetic: "/ˈhoʊmsɪk/", meaning: "Nhớ nhà", example: "I'm feeling a bit homesick.", exampleVi: "Tôi đang hơi nhớ nhà." },
    { word: "Getaway", phonetic: "/ˈɡɛtəweɪ/", meaning: "Chuyến đi ngắn", example: "Let's plan a weekend getaway.", exampleVi: "Mình lên kế hoạch đi chơi cuối tuần." },
    { word: "Sightseeing", phonetic: "/ˈsaɪtsiːɪŋ/", meaning: "Tham quan", example: "We went sightseeing after work.", exampleVi: "Chúng tôi đi tham quan sau giờ làm." },
    { word: "Tip", phonetic: "/tɪp/", meaning: "Mẹo, gợi ý", example: "Do you have any tips for newcomers?", exampleVi: "Bạn có mẹo gì cho người mới không?" },
    { word: "Schedule", phonetic: "/ˈʃɛdjuːl/", meaning: "Lịch trình", example: "What's your schedule like tomorrow?", exampleVi: "Lịch trình ngày mai bạn thế nào?" },
    { word: "Weekend", phonetic: "/ˈwiːkɛnd/", meaning: "Cuối tuần", example: "Any plans for the weekend?", exampleVi: "Cuối tuần có kế hoạch gì không?" },
    { word: "Gym", phonetic: "/dʒɪm/", meaning: "Phòng tập", example: "Is there a gym in the hotel?", exampleVi: "Khách sạn có phòng tập không?" },
    { word: "SIM card", phonetic: "/sɪm kɑːrd/", meaning: "Thẻ SIM", example: "I need to buy a local SIM card.", exampleVi: "Tôi cần mua SIM nội địa." },
    { word: "Adapter", phonetic: "/əˈdæptər/", meaning: "Bộ chuyển đổi ổ cắm", example: "I forgot my power adapter.", exampleVi: "Tôi quên bộ chuyển đổi ổ cắm." },
    { word: "Charger", phonetic: "/ˈtʃɑːrdʒər/", meaning: "Sạc điện thoại", example: "Can I borrow your charger?", exampleVi: "Tôi mượn sạc được không?" },
    { word: "Lost", phonetic: "/lɒst/", meaning: "Bị lạc", example: "I think I'm lost. Can you help?", exampleVi: "Tôi nghĩ tôi bị lạc. Giúp tôi được không?" },
    { word: "Prescription", phonetic: "/prɪˈskrɪpʃn/", meaning: "Đơn thuốc", example: "I need to fill this prescription.", exampleVi: "Tôi cần mua thuốc theo đơn này." },
    { word: "Insurance", phonetic: "/ɪnˈʃʊrəns/", meaning: "Bảo hiểm", example: "Do you have travel insurance?", exampleVi: "Bạn có bảo hiểm du lịch không?" },
    { word: "Flu", phonetic: "/fluː/", meaning: "Cúm", example: "I think I'm coming down with the flu.", exampleVi: "Tôi nghĩ tôi đang bị cúm." },
    { word: "Fever", phonetic: "/ˈfiːvər/", meaning: "Sốt", example: "I have a slight fever.", exampleVi: "Tôi bị sốt nhẹ." },
    { word: "Exhausted", phonetic: "/ɪɡˈzɔːstɪd/", meaning: "Kiệt sức", example: "I'm completely exhausted.", exampleVi: "Tôi kiệt sức hoàn toàn." },
  ],
  conversations: [
    {
      title: "Hỏi đường đi", icon: "🗺️",
      context: "Bạn cần hỏi đường đến một địa điểm khi đi bộ trên phố.",
      dialog: [
        { speaker: "b", label: "You", en: "Excuse me, could you tell me how to get to the nearest supermarket?", vi: "Xin lỗi, bạn chỉ đường đến siêu thị gần nhất được không?" },
        { speaker: "a", label: "Stranger", en: "Sure! Go straight for about 200 meters, then turn right at the traffic lights.", vi: "Được! Đi thẳng khoảng 200m, rẽ phải tại đèn đỏ." },
        { speaker: "b", label: "You", en: "Is it walking distance?", vi: "Có đi bộ được không?" },
        { speaker: "a", label: "Stranger", en: "Yes, it's about a 10-minute walk. You'll see it on your left.", vi: "Có, khoảng 10 phút đi bộ. Bạn sẽ thấy ở bên trái." },
        { speaker: "b", label: "You", en: "Great, thank you so much!", vi: "Tuyệt, cảm ơn rất nhiều!" },
        { speaker: "a", label: "Stranger", en: "You're welcome. Enjoy your stay!", vi: "Không có gì. Chúc ở vui!" },
      ]
    },
    {
      title: "Đi mua sắm", icon: "🛒",
      context: "Bạn đi mua sắm tại cửa hàng gần khách sạn.",
      dialog: [
        { speaker: "b", label: "You", en: "Hi, how much is this jacket?", vi: "Xin chào, áo khoác này bao nhiêu?" },
        { speaker: "a", label: "Staff", en: "It's 49.99 euros. We also have it in black and navy blue.", vi: "49.99 euro. Chúng tôi cũng có màu đen và xanh navy." },
        { speaker: "b", label: "You", en: "Can I try on the navy blue one in size medium?", vi: "Tôi thử cái xanh navy cỡ medium được không?" },
        { speaker: "a", label: "Staff", en: "Of course! The fitting room is over there.", vi: "Tất nhiên! Phòng thử đồ ở đằng kia." },
        { speaker: "b", label: "You", en: "It fits perfectly. I'll take it. Do you accept credit cards?", vi: "Vừa vặn. Tôi lấy cái này. Nhận thẻ tín dụng không?" },
        { speaker: "a", label: "Staff", en: "Yes, we do. Would you like a bag?", vi: "Có. Bạn muốn lấy túi không?" },
        { speaker: "b", label: "You", en: "Yes, please. Thank you!", vi: "Vâng. Cảm ơn!" },
      ]
    },
    {
      title: "Đi taxi / Uber", icon: "🚕",
      context: "Bạn gọi taxi hoặc Uber để di chuyển trong thành phố.",
      dialog: [
        { speaker: "b", label: "You", en: "Hi, could you take me to the Hilton Hotel on Main Street?", vi: "Xin chào, bạn đưa tôi đến khách sạn Hilton trên phố Main được không?" },
        { speaker: "a", label: "Driver", en: "Sure, hop in. Do you know the exact address?", vi: "Được, lên xe đi. Bạn biết địa chỉ chính xác không?" },
        { speaker: "b", label: "You", en: "It's 123 Main Street. How long will it take?", vi: "Số 123 phố Main. Mất bao lâu?" },
        { speaker: "a", label: "Driver", en: "About 15 minutes, depending on traffic.", vi: "Khoảng 15 phút, tùy giao thông." },
        { speaker: "b", label: "You", en: "How much will it cost approximately?", vi: "Chi phí khoảng bao nhiêu?" },
        { speaker: "a", label: "Driver", en: "Around 12 to 15 euros.", vi: "Khoảng 12 đến 15 euro." },
        { speaker: "b", label: "You", en: "Alright, sounds good. Thank you.", vi: "OK, được thôi. Cảm ơn." },
      ]
    },
    {
      title: "Tại khách sạn", icon: "🏨",
      context: "Bạn check-in hoặc cần hỗ trợ tại khách sạn.",
      dialog: [
        { speaker: "b", label: "You", en: "Good evening, I have a reservation under the name [Name].", vi: "Chào buổi tối, tôi có đặt phòng dưới tên [Name]." },
        { speaker: "a", label: "Receptionist", en: "Welcome! Let me find your booking. Yes, a single room for 14 nights. Correct?", vi: "Chào mừng! Để tôi tìm. Vâng, phòng đơn 14 đêm. Đúng không?" },
        { speaker: "b", label: "You", en: "Yes, that's correct. What floor is the room on?", vi: "Vâng, đúng rồi. Phòng ở tầng mấy?" },
        { speaker: "a", label: "Receptionist", en: "Fifth floor, room 512. The elevator is on your right. Breakfast is from 7 to 10.", vi: "Tầng 5, phòng 512. Thang máy bên phải. Bữa sáng từ 7 đến 10 giờ." },
        { speaker: "b", label: "You", en: "Is there a gym and laundry service available?", vi: "Có phòng tập và dịch vụ giặt ủi không?" },
        { speaker: "a", label: "Receptionist", en: "Yes! The gym is on the ground floor. Laundry forms are in your room.", vi: "Có! Phòng tập ở tầng trệt. Phiếu giặt ủi trong phòng." },
        { speaker: "b", label: "You", en: "Perfect, thank you very much!", vi: "Tuyệt, cảm ơn rất nhiều!" },
      ]
    },
    {
      title: "Nói chuyện với hàng xóm / người lạ", icon: "💬",
      context: "Bạn small talk với người gặp trong thang máy hoặc quán cà phê.",
      dialog: [
        { speaker: "a", label: "Stranger", en: "Hi! Are you from around here?", vi: "Chào! Bạn ở gần đây không?" },
        { speaker: "b", label: "You", en: "No, I'm visiting from Vietnam. I'm here for work.", vi: "Không, tôi từ Việt Nam đến. Đến đây công tác." },
        { speaker: "a", label: "Stranger", en: "Oh nice! How long are you staying?", vi: "Ồ hay! Bạn ở bao lâu?" },
        { speaker: "b", label: "You", en: "About two weeks. It's my first time here, actually.", vi: "Khoảng hai tuần. Thực ra là lần đầu tôi đến đây." },
        { speaker: "a", label: "Stranger", en: "Welcome! You should visit the old town, it's beautiful.", vi: "Chào mừng! Bạn nên ghé khu phố cổ, đẹp lắm." },
        { speaker: "b", label: "You", en: "Thanks for the recommendation! I'll check it out this weekend.", vi: "Cảm ơn gợi ý! Tôi sẽ đi cuối tuần này." },
      ]
    },
    {
      title: "Khi bị ốm", icon: "🤒",
      context: "Bạn cảm thấy không khỏe và cần mua thuốc hoặc gặp bác sĩ.",
      dialog: [
        { speaker: "b", label: "You", en: "Excuse me, I'm not feeling well. Is there a pharmacy nearby?", vi: "Xin lỗi, tôi không khỏe. Có nhà thuốc gần đây không?" },
        { speaker: "a", label: "Colleague", en: "There's one downstairs. What's wrong?", vi: "Có một cái ở tầng dưới. Bạn bị sao?" },
        { speaker: "b", label: "You", en: "I have a bad headache and a sore throat.", vi: "Tôi bị đau đầu và đau họng." },
        { speaker: "a", label: "Colleague", en: "You should take some rest. I'll let the team know you're not feeling well.", vi: "Bạn nên nghỉ ngơi. Tôi sẽ báo team bạn không khỏe." },
        { speaker: "b", label: "You", en: "Thank you. I'll go get some medicine and see if I feel better later.", vi: "Cảm ơn. Tôi sẽ đi mua thuốc và xem có đỡ hơn không." },
      ]
    },
  ],
  phrases: [
    { category: "Chào hỏi & Small talk", items: [
      { en: "Hi, how are you doing?", vi: "Chào, bạn thế nào?", usage: "Chào hỏi thân thiện" },
      { en: "Not bad, thanks. And you?", vi: "Không tệ, cảm ơn. Còn bạn?", usage: "Trả lời chào hỏi" },
      { en: "Nice weather today, isn't it?", vi: "Thời tiết đẹp hôm nay, nhỉ?", usage: "Bắt chuyện" },
      { en: "What do you do for fun around here?", vi: "Ở đây bạn hay làm gì vui?", usage: "Hỏi giải trí" },
      { en: "Any plans for the weekend?", vi: "Cuối tuần có kế hoạch gì không?", usage: "Small talk thứ 6" },
      { en: "How's your day going?", vi: "Ngày hôm nay thế nào rồi?", usage: "Chào hỏi đồng nghiệp" },
      { en: "It was nice talking to you!", vi: "Nói chuyện với bạn vui lắm!", usage: "Kết thúc cuộc trò chuyện" },
      { en: "See you tomorrow / later!", vi: "Hẹn gặp lại ngày mai / lát nữa!", usage: "Tạm biệt" },
    ]},
    { category: "Di chuyển & Hỏi đường", items: [
      { en: "How do I get to [place]?", vi: "Tôi đến [nơi] bằng cách nào?", usage: "Hỏi đường" },
      { en: "Is it within walking distance?", vi: "Có đi bộ được không?", usage: "Hỏi khoảng cách" },
      { en: "Which bus/train goes to [place]?", vi: "Xe buýt/tàu nào đi đến [nơi]?", usage: "Giao thông công cộng" },
      { en: "Could you drop me off here, please?", vi: "Bạn cho tôi xuống đây được không?", usage: "Đi taxi" },
      { en: "How much is a single/return ticket?", vi: "Vé một chiều/khứ hồi bao nhiêu?", usage: "Mua vé" },
      { en: "What time is the last train?", vi: "Chuyến tàu cuối lúc mấy giờ?", usage: "Tàu điện" },
      { en: "Is this the right way to the station?", vi: "Đây có phải đường đến ga không?", usage: "Xác nhận đường đi" },
    ]},
    { category: "Khách sạn & Chỗ ở", items: [
      { en: "I have a reservation under [name].", vi: "Tôi có đặt phòng dưới tên [name].", usage: "Check-in" },
      { en: "Could I have an extra pillow?", vi: "Cho tôi thêm gối được không?", usage: "Yêu cầu tại phòng" },
      { en: "The air conditioning isn't working.", vi: "Điều hòa không hoạt động.", usage: "Báo hỏng" },
      { en: "What time is breakfast served?", vi: "Bữa sáng phục vụ mấy giờ?", usage: "Hỏi dịch vụ" },
      { en: "Could you call me a taxi?", vi: "Bạn gọi taxi cho tôi được không?", usage: "Nhờ khách sạn" },
      { en: "I'd like to extend my stay by one night.", vi: "Tôi muốn ở thêm một đêm.", usage: "Gia hạn" },
    ]},
    { category: "Mua sắm & Thanh toán", items: [
      { en: "How much does this cost?", vi: "Cái này bao nhiêu tiền?", usage: "Hỏi giá" },
      { en: "Do you have this in a different size/color?", vi: "Bạn có cỡ/màu khác không?", usage: "Thử đồ" },
      { en: "Can I try this on?", vi: "Tôi thử cái này được không?", usage: "Trong cửa hàng" },
      { en: "I'll take it. / No thanks, just looking.", vi: "Tôi lấy cái này. / Không, tôi chỉ xem thôi.", usage: "Mua/không mua" },
      { en: "Is there a discount?", vi: "Có giảm giá không?", usage: "Hỏi khuyến mãi" },
      { en: "Can I get a refund?", vi: "Tôi có thể hoàn tiền không?", usage: "Đổi trả" },
    ]},
    { category: "Sức khỏe & Tình huống khẩn cấp", items: [
      { en: "I'm not feeling well.", vi: "Tôi không khỏe.", usage: "Bị ốm" },
      { en: "I need to see a doctor.", vi: "Tôi cần gặp bác sĩ.", usage: "Khẩn cấp" },
      { en: "I have a headache / stomachache / fever.", vi: "Tôi bị đau đầu / đau bụng / sốt.", usage: "Mô tả triệu chứng" },
      { en: "Where is the nearest hospital?", vi: "Bệnh viện gần nhất ở đâu?", usage: "Tìm bệnh viện" },
      { en: "I lost my wallet / phone.", vi: "Tôi mất ví / điện thoại.", usage: "Mất đồ" },
      { en: "Can you help me? It's an emergency.", vi: "Bạn giúp tôi được không? Đây là trường hợp khẩn cấp.", usage: "Khẩn cấp" },
    ]},
  ],
};
